// <auto-generated />
using Connection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace av_challenge_api.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20210227182435_ajustandoNombreTablaUsuario")]
    partial class ajustandoNombreTablaUsuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Connection.Entities.PaisEntity", b =>
                {
                    b.Property<int>("IdPais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_PAIS")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoIso")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CODIGO_ISO");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOMBRE");

                    b.HasKey("IdPais");

                    b.HasIndex("CodigoIso")
                        .IsUnique();

                    b.ToTable("PAIS");

                    b.HasData(
                        new
                        {
                            IdPais = 1,
                            CodigoIso = "AR",
                            Nombre = "Argentina"
                        });
                });

            modelBuilder.Entity("Connection.Entities.UsuarioEntity", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_USUARIO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CLAVE");

                    b.Property<string>("Correo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("")
                        .HasColumnName("CORREO");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOMBRE");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("USUARIO");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Usuario")
                        .IsUnique();

                    b.ToTable("USUARIO");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Clave = "challenge2021",
                            Correo = "",
                            Nombre = "José Vásquez",
                            Usuario = "americavirtual@gmail.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
