// <auto-generated />
using Connection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace av_challenge_api.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20210228144800_agregandoClaveForanea")]
    partial class agregandoClaveForanea
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Connection.Entities.CiudadEntity", b =>
                {
                    b.Property<int>("IdCiudad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_CIUDAD")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdPais")
                        .HasColumnType("int")
                        .HasColumnName("ID_PAIS");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOMBRE");

                    b.HasKey("IdCiudad");

                    b.ToTable("CIUDAD");

                    b.HasData(
                        new
                        {
                            IdCiudad = 1,
                            IdPais = 1,
                            Nombre = "Buenos Aires"
                        },
                        new
                        {
                            IdCiudad = 2,
                            IdPais = 1,
                            Nombre = "Córdoba"
                        },
                        new
                        {
                            IdCiudad = 3,
                            IdPais = 1,
                            Nombre = "Rosario"
                        },
                        new
                        {
                            IdCiudad = 4,
                            IdPais = 1,
                            Nombre = "Mar del Plata"
                        },
                        new
                        {
                            IdCiudad = 5,
                            IdPais = 1,
                            Nombre = "San Miguel de Tucumán"
                        },
                        new
                        {
                            IdCiudad = 6,
                            IdPais = 1,
                            Nombre = "Salta"
                        },
                        new
                        {
                            IdCiudad = 7,
                            IdPais = 1,
                            Nombre = "Santa Fe"
                        },
                        new
                        {
                            IdCiudad = 8,
                            IdPais = 1,
                            Nombre = "Corrientes"
                        },
                        new
                        {
                            IdCiudad = 9,
                            IdPais = 1,
                            Nombre = "Bahía Blanca"
                        },
                        new
                        {
                            IdCiudad = 10,
                            IdPais = 1,
                            Nombre = "Resistencia"
                        },
                        new
                        {
                            IdCiudad = 11,
                            IdPais = 2,
                            Nombre = "Sao Paulo"
                        },
                        new
                        {
                            IdCiudad = 12,
                            IdPais = 2,
                            Nombre = "Río de Janeiro"
                        },
                        new
                        {
                            IdCiudad = 13,
                            IdPais = 2,
                            Nombre = "Salvador"
                        },
                        new
                        {
                            IdCiudad = 14,
                            IdPais = 2,
                            Nombre = "Brasilia"
                        },
                        new
                        {
                            IdCiudad = 15,
                            IdPais = 2,
                            Nombre = "Fortaleza"
                        },
                        new
                        {
                            IdCiudad = 16,
                            IdPais = 2,
                            Nombre = "Belo Horizonte"
                        },
                        new
                        {
                            IdCiudad = 17,
                            IdPais = 2,
                            Nombre = "Manaos"
                        },
                        new
                        {
                            IdCiudad = 18,
                            IdPais = 2,
                            Nombre = "Curitiba"
                        },
                        new
                        {
                            IdCiudad = 19,
                            IdPais = 2,
                            Nombre = "Recife"
                        },
                        new
                        {
                            IdCiudad = 20,
                            IdPais = 2,
                            Nombre = "Porto Alegre"
                        },
                        new
                        {
                            IdCiudad = 21,
                            IdPais = 3,
                            Nombre = "Montevideo"
                        },
                        new
                        {
                            IdCiudad = 22,
                            IdPais = 3,
                            Nombre = "Salto"
                        },
                        new
                        {
                            IdCiudad = 23,
                            IdPais = 3,
                            Nombre = "Paysandú"
                        },
                        new
                        {
                            IdCiudad = 24,
                            IdPais = 3,
                            Nombre = "Maldonado"
                        },
                        new
                        {
                            IdCiudad = 25,
                            IdPais = 3,
                            Nombre = "Rivera"
                        },
                        new
                        {
                            IdCiudad = 26,
                            IdPais = 3,
                            Nombre = "Tacuarembó"
                        },
                        new
                        {
                            IdCiudad = 27,
                            IdPais = 3,
                            Nombre = "Melo"
                        },
                        new
                        {
                            IdCiudad = 28,
                            IdPais = 3,
                            Nombre = "Artigas"
                        },
                        new
                        {
                            IdCiudad = 29,
                            IdPais = 3,
                            Nombre = "Mercedes"
                        },
                        new
                        {
                            IdCiudad = 30,
                            IdPais = 3,
                            Nombre = "Minas"
                        });
                });

            modelBuilder.Entity("Connection.Entities.PaisEntity", b =>
                {
                    b.Property<int>("IdPais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_PAIS")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoIso")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CODIGO_ISO");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOMBRE");

                    b.HasKey("IdPais");

                    b.HasIndex("CodigoIso")
                        .IsUnique();

                    b.ToTable("PAIS");

                    b.HasData(
                        new
                        {
                            IdPais = 1,
                            CodigoIso = "AR",
                            Nombre = "Argentina"
                        },
                        new
                        {
                            IdPais = 2,
                            CodigoIso = "BR",
                            Nombre = "Brasil"
                        },
                        new
                        {
                            IdPais = 3,
                            CodigoIso = "UY",
                            Nombre = "Uruguay"
                        });
                });

            modelBuilder.Entity("Connection.Entities.UsuarioEntity", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_USUARIO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CLAVE");

                    b.Property<string>("Correo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("")
                        .HasColumnName("CORREO");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOMBRE");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("USUARIO");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Usuario")
                        .IsUnique();

                    b.ToTable("USUARIO");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Clave = "challenge2021",
                            Correo = "",
                            Nombre = "José Vásquez",
                            Usuario = "americavirtual@gmail.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
